name = "Create Into the Air"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33a077c29b51481244be4d98849369fd24029b8f08d7302bac9ac59f6c5df9a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
no-internal-hashes = false
