name = "Create Into the Air"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5758b534dadf6b87b53c8eb54851b6c15b3a1778127f4fab542de70c23c34488"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
no-internal-hashes = false
