name = "Create Into the Air"
author = "Tenneb22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4233de5e1580f1debd2fcddc892af5fc541f9d62cfedb425c19c9a1a25c4e910"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
no-internal-hashes = false
